import { Request, Response } from 'express';
import { delay } from 'roadhog-api-doc';

export default delay(
  {
    'POST /api/monitor/loginInfo/findByPage/:pageSize/:current': (req: Request, res: Response) => {
      var pageNum = parseInt(req.params.current);
      var pageSize = parseInt(req.params.pageSize);

      return res.send({
        status: 0,
        res: {
          current: pageNum,
          records: [
            {
              createBy: null,
              createTime: null,
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              infoId: 10,
              loginName: 'admin',
              status: '0',
              ipaddr: '192.168.1.138',
              loginLocation: '内网IP',
              browser: 'Chrome 8',
              os: 'Mac OS X',
              msg: '登录成功',
              loginTime: '2020-12-22 14:03:41',
            },
            {
              createBy: null,
              createTime: null,
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              infoId: 9,
              loginName: 'admin',
              status: '0',
              ipaddr: '192.168.1.138',
              loginLocation: '内网IP',
              browser: 'Chrome 8',
              os: 'Mac OS X',
              msg: '登录成功',
              loginTime: '2020-12-22 09:06:31',
            },
            {
              createBy: null,
              createTime: null,
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              infoId: 8,
              loginName: 'admin',
              status: '0',
              ipaddr: '192.168.1.138',
              loginLocation: '内网IP',
              browser: 'Chrome 8',
              os: 'Mac OS X',
              msg: '登录成功',
              loginTime: '2020-12-21 10:29:01',
            },
            {
              createBy: null,
              createTime: null,
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              infoId: 7,
              loginName: 'admin',
              status: '0',
              ipaddr: '127.0.0.1',
              loginLocation: '内网IP',
              browser: 'Chrome 8',
              os: 'Mac OS X',
              msg: '登录成功',
              loginTime: '2020-10-10 15:21:58',
            },
            {
              createBy: null,
              createTime: null,
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              infoId: 6,
              loginName: 'admin',
              status: '0',
              ipaddr: '192.168.1.138',
              loginLocation: '内网IP',
              browser: 'Chrome 8',
              os: 'Mac OS X',
              msg: '登录成功',
              loginTime: '2020-09-29 11:09:48',
            },
            {
              createBy: null,
              createTime: null,
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              infoId: 5,
              loginName: 'admin',
              status: '0',
              ipaddr: '192.168.1.138',
              loginLocation: '内网IP',
              browser: 'Chrome 8',
              os: 'Mac OS X',
              msg: '登录成功',
              loginTime: '2020-09-29 11:08:55',
            },
            {
              createBy: null,
              createTime: null,
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              infoId: 4,
              loginName: 'admin',
              status: '0',
              ipaddr: '127.0.0.1',
              loginLocation: '内网IP',
              browser: 'Chrome 8',
              os: 'Linux',
              msg: '登录成功',
              loginTime: '2020-09-25 17:38:55',
            },
            {
              createBy: null,
              createTime: null,
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              infoId: 3,
              loginName: 'admin',
              status: '0',
              ipaddr: '127.0.0.1',
              loginLocation: '内网IP',
              browser: 'Chrome 8',
              os: 'Windows 10',
              msg: '登录成功',
              loginTime: '2020-09-25 17:36:58',
            },
            {
              createBy: null,
              createTime: null,
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              infoId: 2,
              loginName: 'admin',
              status: '0',
              ipaddr: '127.0.0.1',
              loginLocation: '内网IP',
              browser: 'Chrome 8',
              os: 'Linux',
              msg: '登录成功',
              loginTime: '2020-09-25 16:28:43',
            },
          ],
          total: 10,
        },
      });
    },
    'POST /api/monitor/loginInfo/remove': {
      status: 0,
    },
    'POST /api/monitor/loginInfo/clean': {
      status: 0,
    },
  },
  600,
);
