import { Request, Response } from 'express';
import { delay } from 'roadhog-api-doc';

export default delay(
  {
    'POST /api/monitor/operLog/findByPage/:pageSize/:current': (req: Request, res: Response) => {
      var pageNum = parseInt(req.params.current);
      var pageSize = parseInt(req.params.pageSize);

      return res.send({
        status: 0,
        res: {
          current: pageNum,
          records: [
            {
              createBy: null,
              createTime: null,
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              operId: 4,
              title: '操作日志',
              businessType: 5,
              method: 'com.ruoyi.system.controller.OperLogController.export()',
              requestMethod: 'POST',
              operatorType: 1,
              operName: 'admin',
              deptName: null,
              operUrl: '/monitor/operLog/export',
              operIp: '192.168.1.138',
              operLocation: '内网IP',
              operParam: '[\n\t{\n\t\t"params":{}\n\t}\n]',
              status: 0,
              errorMsg: null,
              operTime: '2020-12-23 09:42:31',
            },
            {
              createBy: null,
              createTime: null,
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              operId: 3,
              title: '操作日志',
              businessType: 5,
              method: 'com.ruoyi.system.controller.OperLogController.export()',
              requestMethod: 'POST',
              operatorType: 1,
              operName: 'admin',
              deptName: null,
              operUrl: '/monitor/operLog/export',
              operIp: '192.168.1.138',
              operLocation: '内网IP',
              operParam: '[\n\t{\n\t\t"params":{}\n\t}\n]',
              status: 0,
              errorMsg: null,
              operTime: '2020-12-23 09:42:22',
            },
            {
              createBy: null,
              createTime: null,
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              operId: 2,
              title: '操作日志',
              businessType: 5,
              method: 'com.ruoyi.system.controller.OperLogController.export()',
              requestMethod: 'POST',
              operatorType: 1,
              operName: 'admin',
              deptName: null,
              operUrl: '/monitor/operLog/export',
              operIp: '192.168.1.138',
              operLocation: '内网IP',
              operParam: '[\n\t{\n\t\t"params":{}\n\t}\n]',
              status: 0,
              errorMsg: null,
              operTime: '2020-12-23 09:24:33',
            },
            {
              createBy: null,
              createTime: null,
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              operId: 1,
              title: '操作日志',
              businessType: 9,
              method: 'com.ruoyi.system.controller.OperLogController.clean()',
              requestMethod: 'POST',
              operatorType: 1,
              operName: 'admin',
              deptName: null,
              operUrl: '/monitor/operLog/clean',
              operIp: '192.168.1.138',
              operLocation: '内网IP',
              operParam: '[]',
              status: 0,
              errorMsg: null,
              operTime: '2020-12-22 14:43:31',
            },
          ],
          total: 4,
        },
      });
    },
    'POST /api/monitor/operLog/remove': {
      status: 0,
    },
    'POST /api/monitor/operLog/clean': {
      status: 0,
    },
  },
  600,
);
