import { Request, Response } from 'express';
import { delay } from 'roadhog-api-doc';

export default delay(
  {
    'POST /api/system/dict/type/findByPage/:pageSize/:current': (req: Request, res: Response) => {
      var pageNum = parseInt(req.params.current);
      var pageSize = parseInt(req.params.pageSize);

      return res.send({
        status: 0,
        res: {
          current: pageNum,
          records: [
            {
              dictId: 1,
              dictName: '操作类型',
              dictType: 'sys_oper_type',
              status: 'TRUE',
              remark: '操作类型列表',
              createTime: '2018-03-16 11:33:00',
            },
          ],
          total: 1,
        },
      });
    },
    'POST /api/system/dict/type/add': {
      status: 0,
    },
    'POST /api/system/dict/type/update': {
      status: 0,
    },
    'POST /api/system/dict/type/remove': {
      status: 0,
    },
    'POST /api/system/dict/data/findByPage/:pageSize/:current': (req: Request, res: Response) => {
      var pageNum = parseInt(req.params.current);
      var pageSize = parseInt(req.params.pageSize);

      return res.send({
        status: 0,
        res: {
          current: pageNum,
          records: [
            {
              createBy: 'admin',
              createTime: '2018-03-16 11:33:00',
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              dictCode: 16,
              dictSort: 1,
              dictLabel: '新增',
              dictValue: '1',
              dictType: 'sys_oper_type',
              cssClass: '',
              listClass: 'info',
              isDefault: 'TRUE',
              status: 'TRUE',
              remark: '新增操作',
            },
            {
              createBy: 'admin',
              createTime: '2018-03-16 11:33:00',
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              dictCode: 17,
              dictSort: 2,
              dictLabel: '修改',
              dictValue: '2',
              dictType: 'sys_oper_type',
              cssClass: '',
              listClass: 'info',
              isDefault: 'TRUE',
              status: 'TRUE',
              remark: '修改操作',
            },
            {
              createBy: 'admin',
              createTime: '2018-03-16 11:33:00',
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              dictCode: 18,
              dictSort: 3,
              dictLabel: '删除',
              dictValue: '3',
              dictType: 'sys_oper_type',
              cssClass: '',
              listClass: 'danger',
              isDefault: 'TRUE',
              status: 'TRUE',
              remark: '删除操作',
            },
            {
              createBy: 'admin',
              createTime: '2018-03-16 11:33:00',
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              dictCode: 19,
              dictSort: 4,
              dictLabel: '授权',
              dictValue: '4',
              dictType: 'sys_oper_type',
              cssClass: '',
              listClass: 'primary',
              isDefault: 'TRUE',
              status: 'TRUE',
              remark: '授权操作',
            },
            {
              createBy: 'admin',
              createTime: '2018-03-16 11:33:00',
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              dictCode: 20,
              dictSort: 5,
              dictLabel: '导出',
              dictValue: '5',
              dictType: 'sys_oper_type',
              cssClass: '',
              listClass: 'warning',
              isDefault: 'TRUE',
              status: 'TRUE',
              remark: '导出操作',
            },
            {
              createBy: 'admin',
              createTime: '2018-03-16 11:33:00',
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              dictCode: 21,
              dictSort: 6,
              dictLabel: '导入',
              dictValue: '6',
              dictType: 'sys_oper_type',
              cssClass: '',
              listClass: 'warning',
              isDefault: 'TRUE',
              status: 'TRUE',
              remark: '导入操作',
            },
            {
              createBy: 'admin',
              createTime: '2018-03-16 11:33:00',
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              dictCode: 22,
              dictSort: 7,
              dictLabel: '强退',
              dictValue: '7',
              dictType: 'sys_oper_type',
              cssClass: '',
              listClass: 'danger',
              isDefault: 'TRUE',
              status: 'TRUE',
              remark: '强退操作',
            },
            {
              createBy: 'admin',
              createTime: '2018-03-16 11:33:00',
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              dictCode: 23,
              dictSort: 8,
              dictLabel: '生成代码',
              dictValue: '8',
              dictType: 'sys_oper_type',
              cssClass: '',
              listClass: 'warning',
              isDefault: 'TRUE',
              status: 'TRUE',
              remark: '生成操作',
            },
            {
              createBy: 'admin',
              createTime: '2018-03-16 11:33:00',
              updateBy: null,
              updateTime: null,
              searchValue: null,
              beginTime: null,
              endTime: null,
              params: {},
              dictCode: 24,
              dictSort: 8,
              dictLabel: '清空数据',
              dictValue: '9',
              dictType: 'sys_oper_type',
              cssClass: '',
              listClass: 'danger',
              isDefault: 'TRUE',
              status: 'TRUE',
              remark: '清空操作',
            },
          ],
          total: 1,
        },
      });
    },
    'POST /api/system/dict/data/add': {
      status: 0,
    },
    'POST /api/system/dict/data/update': {
      status: 0,
    },
    'POST /api/system/dict/data/remove': {
      status: 0,
    },
  },
  600,
);
